name: Licensed

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: meta-introspector/checkout@main
      - run: npm ci
      - run: npm run licensed-check